[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "Linux for Power users"
# "description": "Linux tutorial and training course for people who have no, or very little experience with Linux/Unix. Background and the use of the command line.",

# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/slides"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://github.com/szabgab/slides/edit/main/linux/{path}"

[output.markdown]

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"




